#app/core/synonyms.py

# Verb synonym mapping for semantic alignment
VERB_SYNONYMS = {
    "develop": ["design", "build", "implement", "create", "engineer", "code", "craft", "produce", "construct", "author", "compose","work"],
    "implement": ["execute", "deploy", "integrate", "apply", "realize", "carry out", "actualize", "instantiate"],
    "design": ["architect", "plan", "prototype", "model", "draft", "sketch", "formulate", "structure"],
    "lead": ["manage", "supervise", "coordinate", "head", "oversee", "direct", "orchestrate", "organize", "guide", "drive"],
    "mentor": ["guide", "coach", "train", "provide guidance", "assist junior developers", "advise", "support learning", "teach", "assist","help"],
    "optimize": ["improve", "enhance", "refactor", "streamline", "tune", "boost", "accelerate", "fine-tune", "maximize efficiency"],
    "test": ["validate", "verify", "perform unit testing", "perform integration testing", "QA", "debug", "inspect", "check correctness"],
    "analyze": ["evaluate", "assess", "review", "debug", "investigate", "examine", "study", "audit", "inspect data"],
    "deploy": ["release", "launch", "push to production", "deliver", "roll out", "ship", "install"],
    "monitor": ["observe", "track", "log", "maintain", "report metrics", "supervise", "watch", "audit", "check performance"],
    "maintain": ["support", "update", "upgrade", "fix bugs", "sustain", "manage", "keep running","follow","help"],
    "integrate": ["combine", "connect", "link systems", "orchestrate services", "merge", "unify", "synchronize", "connect APIs"],
    "automate": ["script", "schedule", "configure pipelines", "build automation", "set up automated workflows", "program automatic tasks"],
    "document": ["write documentation", "create manuals", "record procedures", "document processes", "log", "note", "prepare guides"],
    "collaborate": ["coordinate", "work with", "partner with", "teamwork", "cooperate", "join forces", "liaise", "communicate", "participate", "willingness", "contribute"],
    "research": ["investigate", "experiment", "explore new solutions", "study", "analyze trends", "probe", "examine"],
    "optimize performance": ["reduce latency", "improve throughput", "enhance efficiency", "speed up", "boost performance", "refine execution"],
    "establish": ["own", "take ownership", "manage ownership", "set up", "found", "create responsibility", "define processes"],
    "identify": ["detect", "recognize", "spot", "find", "pinpoint", "discover", "determine"],
    "resolve": ["fix", "correct", "address", "remediate", "solve", "troubleshoot", "rectify"],
    "scale": ["optimize for performance", "make scalable", "expand capacity", "grow", "handle increased load", "enhance scalability"],
    "optimize code": ["refactor", "improve code", "enhance efficiency", "streamline algorithms","write"],
    "configure": ["set up", "adjust", "tune settings", "customize", "initialize"],
    "analyze data": ["process data", "evaluate datasets", "interpret results", "extract insights", "scrutinize information"],
    "review": ["audit", "inspect", "check", "examine", "evaluate", "assess quality"],
    "create": ["build", "develop", "design", "produce", "generate", "construct"],
    "maintain systems": ["support infrastructure", "manage systems", "ensure uptime", "administer", "monitor"],
    "lead project": ["coordinate project", "manage initiative", "direct efforts", "oversee task", "head team"],
    "experience": ["proficient", "expert", "expertise","exposure", "solid understanding", "understand", "strong understanding", "proficiency","adept"],
    "reduce":["minimize", "lower", "slash"],
    "conduct":["orchestrate", "organize", "organise","lead","did", "participate","introduce"],
    
}

SKILL_SYNONYMS = {
    "cicd pipelines": [
        "continuous integration", "continuous deployment", "ci/cd", "build pipelines",
        "release pipelines", "cicd pipelines", "cicd tools", "cicd", "jenkins"
    ],
    "rest api": [
        "restful api", "restful apis", "api design", "web services",
        "api development", "api integration", "rest api integration"
    ],
    "aws": ["aws cloud", "amazon web services","cloud infrastructure", "cloud computing"],
    "azure": ["azure cloud", "microsoft azure", "cloud infrastructure", "cloud computing"],
    "gcp": ["google cloud", "google cloud platform", "cloud infrastructure", "cloud computing"],
    "docker": ["containers", "containerization", "docker container", "docker-compose"],
    "kubernetes": ["k8s", "container orchestration"],
    "python": ["python 3", "python programming", "py"],
    "java": ["java 8", "java 11", "java programming"],
    "javascript": ["js", "node.js", "nodejs", "typescript","ecmascript","scripting"],
    "react": ["react.js", "reactjs", "frontend framework","react framework"],
    "angular":["angularjs","angular framework","frontend framework","front-end framework"],
    "vue":["vue.js","vue js","vue framework","frontend framework","front-end framework"],
    "spring boot": ["spring", "springframework", "java spring boot", "spring mvc"],
    "django": ["python django", "django framework"],
    "sql": ["postgresql", "mysql", "oracle sql", "database query"],
    "html":["markup languages","html5"],
    "web application development":["frontend development","web development", "front-end development","spa","single page applications","browser apps","browser applications"],
    "css":["styling","css3","stylesheet", "cascading style sheets", "responsive design"],
    "nosql": ["mongodb", "cassandra", "redis", "document db"],
    "git": ["git version control", "gitlab", "github", "version control systems", "gerrit"],
    "jenkins": ["ci tool", "build automation"],
    "jira": ["project tracking", "agile tool"],
    "unit testing": ["test cases", "junit", "pytest", "testing framework","test strategy","test case design"],
    "testing":["regression testing","regression","accessibility testing", "unit testing","regression test","smoke test","sanity test", "test","jest", "frontend testing","quality assurance","qa","qa adherence","quality adherence"],
    "integration testing": ["end-to-end testing", "e2e tests"],
    "automation frameworks": ["automation testing", "selenium", "robot framework", "testng", "automation tests", "automated regression tests", "automated test","qa automation"],
    "docker-compose": ["docker compose", "multi-container setup"],
    "ansible": ["configuration management", "infrastructure automation"],
    "terraform": ["infrastructure as code", "iac"],
    "aws lambda": ["serverless functions"],
    "sagemaker" :["sagemaker pipelines", "aws sagemaker pipelines"],
    "cloud architecture": ["cloud solutions", "cloud engineering", "cloud infrastructure"],
    "microservices": ["service-oriented architecture", "soa", "backend architecture", "scalable backend systems", "backend systems"],
    "data engineering": ["etl pipelines", "data pipelines", "big data","data mining","model training pipelines"],
    "machine learning": ["ml", "mlops", "predictive modeling"],
    "devops": ["site reliability engineering", "sre", "ops automation"],
    "scrum": ["agile", "scrum master", "kanban","agile methodologies","agile development"],
    "agile methodologies": ["agile practices", "sprint planning", "iteration planning", "agile ceremonies"],
    "scalable": ["scalable backend systems", "scalability design", "performance optimization", "scalable systems","scalability"],
    "backend architecture": ["microservices architecture", "scalable backend systems", "system design"],
    "sdlc" : ["software development life cycle","cloud-native application development", "application development","enterprise-grade application","rapid application development", "software lifecycle management","full software lifecycle management"],
    "operating systems":["os", "linux", "ubuntu", "windows","macos", "macintosh", "fedora", "centos", "redhat"],
    "forecasting":["demand forecasting","forecasting algorithms","time series forecasting","forecasting pipelines", "mape","automated forecasting"],
    "statistical modeling" : ["statistical modeling data analysis tools","statistical techniques", "statistical algorithms", "probability", "risk functions","model training pipelines", "model training"],
    "dashboards":["data visualisation", "data visualization","architecture diagrams"],
    "code debugging": ["secure coding", "secure coding practices", "debugging", "code analysis","coding hygiene","detect anomalies", "detect anomaly", "coding best practices", "coding best practice"],
    "continuous improvement": ["system resiliency", "retry strategy", "retry strategies", "distributed tracing","system modernization","raising code coverage","improve data retrieval"],
    "design patterns":["design pattern", "design artifacts","design constraints","system design patterns", "system design","application design","full stack design","full-stack design", "design systems", "solid principles","oops","object oriented programming","oop"],
    "software components":["scalable software applications", "business software components","high-quality applications", "high quality applications","component design","web application development","feature design"],
    "ui":["ui design", "ux design","user experience design", "user interface design","frontend design", "front-end design", "ui applications","ui application","ui/ux design","frontend","front-end","webpage developement", "web application development","user-centric design","interaction design","visual design","interface design"],
    "virtual reality":["augmented reality","augmented reality development","virtual reality development"],
    "guidance":["mentor","mentoring juniors","assisting juniors","code review","review","assist","peer review","peer reviews"],
    "automation pipelines":["qa automation", "release automation", "pipeline automation","process automation"],
    "bdd":["behavior driven development","behaviour driven development"],
    "ddd":["domain-driven design","domain driven design","domain-driven development","domain driven development"],
    "tdd":["test driven development","test-driven development","test driven design","test-driven design"],
    "ide": ["integrated development environment","eclipse","intellij","intellij idea","visual studio","vs code","vscode","pycharm","netbeans","android studio","xcode","rider","atom","sublime text","komodo ide","bluej","jdeveloper","light ide"],
    "process automation":["performance improvements","performance improvement","performance optimization","application performance monitoring"],

    
}

QUALIFICATION_SYNONYMS = {
    "software engineering": [
        "software engineering", "computer science", "information technology",  "it", "b.tech in software engineering",
        "b.sc computer science", "bachelor of technology", "bachelor of engineering", "b.s. computer science", "computer engineering","bs"
    ],
    "bachelor's degree": [
        "b.sc", "b.tech", "bachelor of technology", "bachelor of science", "bachelor of engineering", "ba", "b-tech", "btech", "be", "b.e", "b.s. computer science", "bs"
    ],
    "master's degree": [
        "m.sc", "m.tech", "master of science", "master of technology", "ms", "ma",
    ],
    "data science":["data analytics", "business analytics","data analysis", "data engineering"],
}

LANGUAGE_CANONICAL = {
    "python programming language": "python",
    "java programming language": "java",
    "c programming language": "c",
    "c++ programming language": "c++",
    "c# programming language": "c#",
    "javascript programming language": "javascript",
    "typescript programming language": "typescript",
    "kotlin programming language": "kotlin",
    "scala programming language": "scala",
    "ruby programming language": "ruby",
    "php programming language": "php",
    "swift programming language": "swift",
    "perl programming language": "perl",
    "haskell programming language": "haskell",
    "matlab programming language": "matlab",
    "r programming language": "r",
    "dart programming language": "dart",
    "network security" : "network",
    "game development" : "game",
}